[phases.install]
cmds = [
   'rm -rf LibraryManagement.Tests',
   'dotnet restore library-management.csproj',
]

[phases.build]
cmds = [
   'dotnet publish --no-restore library-management.csproj -c Release -o out',
]

[start]
cmd = 'out/library-management'
