[phases.install]
cmds = ['dotnet restore /app/library-management/library-management.csproj']

[phases.build]
cmds = ['dotnet pubish --no-restore /app/library-management/library-management.csproj -c Release -o out']

[start]
cmd = '/app/out/library-management'
